### ISSUE TITLE
Unexpected Code Pair error due to XRecord?

### ISSUE THREAD

**Issue by Vadoola** [Vadoola/dxf2elmt#19]
Laurent [tried to convert a file ](https://qelectrotech.org/forum/viewtopic.php?pid=20379#p20379) that was giving a error about it being an invalid DXF due to an unexpected code pair.

A quick glance, it looks like the issue is due to an XRecord, and **_might_** be in the underlying dxf crate, but I need to look at this more closely. 
[05DI-AD16DIX-10.zip](https://github.com/user-attachments/files/17183277/05DI-AD16DIX-10.zip)

**Comment by scorpio810** [comment]
It seems that the issue is fixed with the master branch of dxf-rs 
and patched polygon.rs https://qelectrotech.org/forum/viewtopic.php?pid=20519#p20519

**Comment by Vadoola** [comment]
This issue was fixed with the upgrade from dxf-rs 0.5.0 to dxf-rs master branch on git as part of commit 01cbabd
